# Generated by Django 2.2.1 on 2020-01-30 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.IntegerField(default=0, verbose_name='CMND')),
                ('username', models.CharField(max_length=50, verbose_name='Tên Khách Hàng')),
                ('phone', models.CharField(max_length=30, verbose_name='Số Điện Thoại')),
                ('number_ticket', models.CharField(max_length=50, verbose_name='Số Vé Mua')),
                ('deposit', models.CharField(max_length=50, verbose_name='Tiền Đặt Cọc')),
                ('money', models.CharField(max_length=50, verbose_name='Tiền Còn Thiếu')),
                ('create_date', models.DateField(default=datetime.date.today, verbose_name='Ngày Nhập')),
                ('start_date', models.DateField(verbose_name='Ngày Đi Tàu')),
                ('start_time_train', models.CharField(max_length=50, verbose_name='Giờ Đi')),
                ('note', models.TextField(max_length=2000, verbose_name='Ghi Chú')),
                ('status', models.IntegerField(default=0, verbose_name='Trạng Thái')),
            ],
        ),
    ]
