# Generated by Django 2.2.1 on 2020-01-15 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('number_ticket', models.CharField(max_length=50)),
                ('deposit', models.CharField(max_length=50)),
                ('money', models.CharField(max_length=50)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('start_date', models.DateField()),
                ('start_time_train', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
