# Generated by Django 2.2.1 on 2020-01-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmnd', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('number_ticket', models.CharField(max_length=50)),
                ('deposit', models.CharField(max_length=50)),
                ('money', models.CharField(max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('start_time_train', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='debt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='debt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paydebt',
            name='company',
        ),
        migrations.RemoveField(
            model_name='paydebt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='point',
            name='user',
        ),
        migrations.RemoveField(
            model_name='priceticket',
            name='company',
        ),
        migrations.RemoveField(
            model_name='priceticket',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='company',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='train',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='company',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='train',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Debt',
        ),
        migrations.DeleteModel(
            name='PayDebt',
        ),
        migrations.DeleteModel(
            name='Point',
        ),
        migrations.DeleteModel(
            name='PriceTicket',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='Train',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
