# Generated by Django 2.2.1 on 2020-01-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0002_auto_20200113_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cmnd',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
