# Generated by Django 2.2.1 on 2020-01-14 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0004_auto_20200114_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
