# Generated by Django 2.2.1 on 2020-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0005_auto_20200130_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='end_time_train',
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_time_train',
            field=models.CharField(max_length=50, verbose_name='Giờ Đi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Vé Mới Đặt'), (1, 'Vé Đã Thanh Toán'), (2, 'Vé Hủy'), (3, 'Vé Không Đi')], default=0, verbose_name='Trạng Thái'),
        ),
    ]
